### ISSUE TITLE
GitHub Actions for building/testing biber fails

### ISSUE THREAD

**Issue by vadimkantorov** [plk/biber#470]
Based on your GH Action https://github.com/plk/biber/blob/dev/.github/workflows/main.yml, I wrote the following one which I run in my own repo.

I am getting the following test error. How can I fix this? Thanks :)

Full log: 
[log.txt](https://github.com/plk/biber/files/14223683/log.txt)

```
Installing /home/runner/work/busyperl/localperl/man/man3/Test::Differences.3
  DCANTRELL/Test-Differences-0.71.tar.gz
  /usr/bin/make install  -- OK
t/annotations.t ........... ok
t/basic-misc.t ............ ok
t/bcfvalidation.t ......... ok
t/biblatexml.t ............ ok
t/bibtex-aliases.t ........ ok
t/bibtex-output.t ......... ok
t/configfile.t ............ ok
t/crossrefs.t ............. ok
t/datalists.t ............. ok
t/dateformats.t ........... ok
t/dm-constraints.t ........ ok
t/encoding.t .............. ok
t/extradate.t ............. ok
t/extratitle.t ............ ok
t/extratitleyear.t ........ ok
t/full-bbl.t .............. ok
t/full-bblxml.t ........... ok
t/full-bibtex.t ........... ok
t/full-dot.t .............. ok
t/labelalpha.t ............ ok
t/labelalphaname.t ........ ok
t/labelname.t ............. ok
t/langtags.t .............. ok
t/maps.t .................. ok
t/names.t ................. ok
t/names_x.t ............... ok
t/options.t ............... ok
t/related-entries.t ....... ok

#   Failed test 'Fetch from plain bib download'
#   at t/remote-files.t line 91.
# --- Got
# +++ Expected
# @@ -25,6 +25,7 @@
#        \\field{labeldatesource}{}
#        \\field{labelnamesource}{author}
#        \\field{labeltitlesource}{title}
# +      \\field{journaltitle}{Artificial Intelligence}
#        \\field{title}{Approximating {MAP}s for belief networks is {NP}-hard and other theorems}
#        \\field{volume}{102}
#        \\field{year}{1998}
# Looks like you failed 1 test of 1.
t/remote-files.t .......... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/sections-complex.t ...... ok
t/sections.t .............. ok
t/set-dynamic.t ........... ok
t/set-legacy.t ............ ok
t/set-static.t ............ ok
t/skips.t ................. ok
t/skipsg.t ................ ok
t/sort-case.t ............. ok
t/sort-complex.t .......... ok
t/sort-names.t ............ ok
t/sort-order.t ............ ok
t/sort-uc.t ............... ok
t/sorting.t ............... ok
t/tool-bltxml-inout.t ..... ok
t/tool-bltxml.t ........... ok
t/tool-config.t ........... ok
t/tool.t .................. ok
t/translit.t .............. ok
t/truncation.t ............ ok
t/uniqueness-nameparts.t .. ok
t/uniqueness.t ............ ok
t/utils.t ................. ok
t/xdata.t ................. ok

Test Summary Report
-------------------
t/remote-files.t        (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
```

```yaml
name: buildbiberdeps

env:
  URLPERL: https://www.cpan.org/src/5.0/perl-5.32.0.tar.gz
  MAKEFLAGS: -j2
  BIBER_DEV_TESTS: 1

on: workflow_dispatch

jobs:
  buildbiberdeps:
    runs-on: ubuntu-22.04
    steps:
       - name: Install Perl
         run: |
           mkdir perlsource
           wget -nc $URLPERL
           tar -xf $(basename $URLPERL) --strip-components=1 --directory=perlsource

           pushd perlsource
           bash +x ./Configure -sde -Dprefix="$RUNNER_WORKSPACE/localperl"
           test -f Makefile
           make
           make install
           popd

       - name: Set ENV
         run: |
           echo "$RUNNER_WORKSPACE/localperl/bin" >> $GITHUB_PATH
           echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RUNNER_WORKSPACE/localperl/lib" >> $GITHUB_ENV

       - name: Install Biber
         run: git clone https://github.com/plk/biber

       - name: Install Biber Dependencies Without Test
         run: |
           cd biber
           cpan -T Module::Build
           perl Build.PL
           perl ./Build installdeps --cpan_client "cpan -T"
           perl ./Build test
```
